#!/bin/bash

# Load parameters
. git-nas-param

# This script assumes that you are placed in the project folder!
PROJECT_NAME=$(basename `pwd`)
GIT_SUFFIX=".git"
REPO_NAME="$PROJECT_NAME$GIT_SUFFIX"

echo "A git repository will be created with name $REPO_NAME"
read -p "Are you sure? " -n 1 -r
echo    # (optional) move to a new line
if [[ $REPLY =~ ^[Yy]$ ]]
then

# Create the git folder on the server side
mkdir ../$REPO_NAME
cd ../$REPO_NAME
git init --bare --shared=group
cd ../$PROJECT_NAME
echo `scp -P $PORT -r ../$REPO_NAME $USER@$ADDRESS:$REPOS_PATH`
# Change group owner to distant git group
echo `ssh -p $PORT $USER@$ADDRESS chgrp -R $SHARE_GROUP $REPOS_PATH$REPO_NAME`
echo `ssh -p $PORT $USER@$ADDRESS chmod -R =770 $REPOS_PATH$REPO_NAME`

# Clean the bare repo
rm -rf ../$REPO_NAME

# Populate the git repo
git init
git config --global user.email "$EMAIL"
git config --global user.name "$NAME"
git add .
git commit -m "Initial commit"
git remote add origin ssh://$USER@$ADDRESS:$PORT$REPOS_PATH$REPO_NAME
git push -u origin master

touch .git/repo-name
echo $REPO_NAME > .git/repo-name
fi
